node("Deployment-Server"){

  // Get the Image

  def IMAGE="${ARTIFACTS}"
  def NAMESPACE="osgroup-techies"
  def APP_NAME="cddemo"
  

  // Stage 1 : Checkout SCM

  stage("Get the Deployment Artifacts"){
     
    checkout scm

      stage ("Get The Latest Changes") {
        sh ('git log  --pretty=format:"%Cred%an - %ar%n %Cblue %h -%Cgreen %s %n" -n 5')
      }

  }


  // --------------------------------------------------------------

 
  // Stage 2: Create The Deploy Artifacts
  
  stage ("Create The App Manifests"){
  
    dir("cddemo"){
      
       sh("chmod u+x app")
    
       sh(". ./app ; export IMAGE=${IMAGE}; envsubst < app.yml >app_manifest.yml")


       stage("Apply The Manifests"){

           sh("sudo kubectl apply -f app_manifest.yml")
       }
     
       stage("Image Rollout Status"){
          
          stage("Switching Context To Current Namespace"){
    
            sh("sudo kubectl config set-context --current --namespace=${NAMESPACE}")


          }
          
          stage ("Image Rollout Status"){
            sh("sudo kubectl rollout status deployment ${APP_NAME}") 
          }
       }

    }

  }  
  


}

